server:
  port: 8860

spring:
  application:
    name: nacos-config
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

nacos:
  cofing:
    name : nacosconfig
    function: study