server:
  port : 8858 # 当前工程的端口
spring:
  application:
    name: nacos-provider # 当前工程的应用名
  cloud:
    sentinel:
      transport:
        # Sentinel DashBoard的地址
        port: 8719
        # 这个端口配置会在应用对应的机器上启动一个 Http Server，该 Server 会与 Sentinel 控制台做交互。比如 Sentinel 控制台添加了1个限流规则，会把规则数据 push 给这个 Http Server 接收，Http Server 再将规则注册到 Sentinel 中
        dashboard: localhost:8861
#        clientIp: localhost:8858

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos server 的地址
